# Generated by Django 3.1.3 on 2020-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_condition_id', models.IntegerField(default=5)),
                ('category_name', models.CharField(default='', max_length=1000)),
                ('brand_name', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=12)),
                ('shipping', models.BooleanField(default=False)),
                ('item_description', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
