category_map = {
    1: "Beauty/Bath & Body/Bathing Accessories",
    2: "Beauty/Bath & Body/Bath",
    3: "Beauty/Bath & Body/Cleansers",
    4: "Beauty/Bath & Body/Other",
    5: "Beauty/Bath & Body/Scrubs & Body Treatments",
    6: "Beauty/Bath & Body/Sets",
    7: "Beauty/Fragrance/Candles & Home Scents",
    8: "Beauty/Fragrance/Kids",
    9: "Beauty/Fragrance/Men",
    10: "Beauty/Fragrance/Other",
    11: "Beauty/Fragrance/Sets",
    12: "Beauty/Fragrance/Women",
    13: "Beauty/Hair Care/Conditioners",
    14: "Beauty/Hair Care/Hair & Scalp Treatments",
    15: "Beauty/Hair Care/Hair Color",
    16: "Beauty/Hair Care/Hair Loss Products",
    17: "Beauty/Hair Care/Hair Perms & Texturizers",
    18: "Beauty/Hair Care/Hair Relaxers",
    19: "Beauty/Hair Care/Other",
    20: "Beauty/Hair Care/Shampoo & Conditioner Sets",
    21: "Beauty/Hair Care/Shampoo Plus Conditioner",
    22: "Beauty/Hair Care/Shampoos",
    23: "Beauty/Hair Care/Styling Products",
    24: "Beauty/Hair Care/Styling Tools",
    25: "Beauty/Makeup/Body",
    26: "Beauty/Makeup/Brushes & Applicators",
    27: "Beauty/Makeup/Eyes",
    28: "Beauty/Makeup/Face",
    29: "Beauty/Makeup/Lips",
    30: "Beauty/Makeup/Makeup Palettes",
    31: "Beauty/Makeup/Makeup Remover",
    32: "Beauty/Makeup/Makeup Sets",
    33: "Beauty/Makeup/Nails",
    34: "Beauty/Makeup/Other",
    35: "Beauty/Other/Other",
    36: "Beauty/Skin Care/Body",
    37: "Beauty/Skin Care/Eyes",
    38: "Beauty/Skin Care/Face",
    39: "Beauty/Skin Care/Feet",
    40: "Beauty/Skin Care/Hands & Nails",
    41: "Beauty/Skin Care/Lips",
    42: "Beauty/Skin Care/Maternity",
    43: "Beauty/Skin Care/Other",
    44: "Beauty/Skin Care/Sets & Kits",
    45: "Beauty/Skin Care/Sun",
    46: "Beauty/Tools & Accessories/Bags & Cases",
    47: "Beauty/Tools & Accessories/Bathing Accessories",
    48: "Beauty/Tools & Accessories/Cotton & Swabs",
    49: "Beauty/Tools & Accessories/Epilators",
    50: "Beauty/Tools & Accessories/Hair Coloring Tools",
    51: "Beauty/Tools & Accessories/Hair Styling Tools",
    52: "Beauty/Tools & Accessories/Makeup Brushes & Tools",
    53: "Beauty/Tools & Accessories/Mirrors",
    54: "Beauty/Tools & Accessories/Nail Tools",
    55: "Beauty/Tools & Accessories/Other",
    56: "Beauty/Tools & Accessories/Toiletry Kits",
    57: "Beauty/Tools & Accessories/Tweezers",
    58: "Beauty/Tools & Accessories/Waxing",
    59: "Electronics/Cameras & Photography/Binoculars & Telescopes",
    60: "Electronics/Cameras & Photography/Camcorders",
    61: "Electronics/Cameras & Photography/Camera & Photo Accessories",
    62: "Electronics/Cameras & Photography/Digital Cameras",
    63: "Electronics/Cameras & Photography/Film Photography",
    64: "Electronics/Cameras & Photography/Flashes & Flash Accessories",
    65: "Electronics/Cameras & Photography/Lenses & Filters",
    66: "Electronics/Cameras & Photography/Lighting & Studio",
    67: "Electronics/Cameras & Photography/Other",
    68: "Electronics/Cameras & Photography/Tripods & Supports",
    69: "Electronics/Car Audio, Video & GPS/Car Security & Convenience",
    70: "Electronics/Car Audio, Video & GPS/Car Speakers & Systems",
    71: "Electronics/Car Audio, Video & GPS/Car Stereos & Components",
    72: "Electronics/Car Audio, Video & GPS/Car Subwoofers",
    73: "Electronics/Car Audio, Video & GPS/Car Video",
    74: "Electronics/Car Audio, Video & GPS/GPS Accessories & Mounts",
    75: "Electronics/Car Audio, Video & GPS/GPS Units & Equipment",
    76: "Electronics/Car Audio, Video & GPS/Other",
    77: "Electronics/Car Audio, Video & GPS/Other Accessories",
    78: "Electronics/Cell Phones & Accessories/Batteries",
    79: "Electronics/Cell Phones & Accessories/Cables & Adapters",
    80: "Electronics/Cell Phones & Accessories/Cases, Covers & Skins",
    81: "Electronics/Cell Phones & Accessories/Cell Phone Accessories",
    82: "Electronics/Cell Phones & Accessories/Cell Phones & Smartphones",
    83: "Electronics/Cell Phones & Accessories/Chargers & Cradles",
    84: "Electronics/Cell Phones & Accessories/Headsets",
    85: "Electronics/Cell Phones & Accessories/Other",
    86: "Electronics/Cell Phones & Accessories/Screen Protectors",
    87: "Electronics/Computers & Tablets/Components & Parts",
    88: "Electronics/Computers & Tablets/Desktops & All-In-Ones",
    89: "Electronics/Computers & Tablets/Drives, Storage & Media",
    90: "Electronics/Computers & Tablets/iPad/Tablet/eBook Access",
    91: "Electronics/Computers & Tablets/iPad/Tablet/eBook Readers",
    92: "Electronics/Computers & Tablets/Laptops & Netbooks",
    93: "Electronics/Computers & Tablets/Networking & Connectivity",
    94: "Electronics/Computers & Tablets/Other",
    95: "Electronics/Computers & Tablets/Printers, Scanners & Supplies",
    96: "Electronics/Media/Blu-Ray",
    97: "Electronics/Media/CD",
    98: "Electronics/Media/DVD",
    99: "Electronics/Media/Other",
    100: "Electronics/Media/VHS",
    101: "Electronics/Other/Other",
    102: "Electronics/TV, Audio & Surveillance/DVD & Blu-ray Players",
    103: "Electronics/TV, Audio & Surveillance/Gadgets",
    104: "Electronics/TV, Audio & Surveillance/Headphones",
    105: "Electronics/TV, Audio & Surveillance/Home Audio",
    106: "Electronics/TV, Audio & Surveillance/Home Speakers & Subwoofers",
    107: "Electronics/TV, Audio & Surveillance/Home Surveillance",
    108: "Electronics/TV, Audio & Surveillance/Other",
    109: "Electronics/TV, Audio & Surveillance/Portable Audio & Accessories",
    110: "Electronics/TV, Audio & Surveillance/Televisions",
    111: "Electronics/Video Games & Consoles/Accessories",
    112: "Electronics/Video Games & Consoles/Consoles",
    113: "Electronics/Video Games & Consoles/Games",
    114: "Electronics/Video Games & Consoles/Other",
    115: "Electronics/Video Games & Consoles/Replacement Parts & Tools",
    116: "Electronics/Video Games & Consoles/Strategy Guides",
    117: "Electronics/Video Games & Consoles/Video Gaming Merchandise",
    118: "Handmade/Accessories/Apron",
    119: "Handmade/Accessories/Case",
    120: "Handmade/Accessories/Charm",
    121: "Handmade/Accessories/Eyewear",
    122: "Handmade/Accessories/Gloves",
    123: "Handmade/Accessories/Hair",
    124: "Handmade/Accessories/Hat",
    125: "Handmade/Accessories/Keychain",
    126: "Handmade/Accessories/Lanyard",
    127: "Handmade/Accessories/Leg Warmers",
    128: "Handmade/Accessories/Men",
    129: "Handmade/Accessories/Mirror",
    130: "Handmade/Accessories/Other",
    131: "Handmade/Accessories/Patch",
    132: "Handmade/Accessories/Pin",
    133: "Handmade/Accessories/Pinback Button",
    134: "Handmade/Accessories/Scarf",
    135: "Handmade/Accessories/Wallet",
    136: "Handmade/Accessories/Watch",
    137: "Handmade/Accessories/Women",
    138: "Handmade/Art/Collages",
    139: "Handmade/Art/Drawings",
    140: "Handmade/Art/Fiber Art",
    141: "Handmade/Art/Illustration",
    142: "Handmade/Art/Mixed Media",
    143: "Handmade/Art/Other",
    144: "Handmade/Art/Painting",
    145: "Handmade/Art/Photography",
    146: "Handmade/Art/Print",
    147: "Handmade/Art/Printmaking",
    148: "Handmade/Art/Sculptures",
    149: "Handmade/Bags and Purses/Backpack",
    150: "Handmade/Bags and Purses/Clutch",
    151: "Handmade/Bags and Purses/Hip Bag",
    152: "Handmade/Bags and Purses/Laptop",
    153: "Handmade/Bags and Purses/Other",
    154: "Handmade/Bags and Purses/Pouch",
    155: "Handmade/Bags and Purses/Purse",
    156: "Handmade/Bags and Purses/Tote",
    157: "Handmade/Bags and Purses/Wallet",
    158: "Handmade/Bags and Purses/Wristlet",
    159: "Handmade/Books and Zines/Album",
    160: "Handmade/Books and Zines/Book",
    161: "Handmade/Books and Zines/Bookmark",
    162: "Handmade/Books and Zines/Comic",
    163: "Handmade/Books and Zines/Journal",
    164: "Handmade/Books and Zines/Other",
    165: "Handmade/Candles/Bookmark",
    166: "Handmade/Candles/Cards",
    167: "Handmade/Candles/Other",
    168: "Handmade/Candles/Stationery",
    169: "Handmade/Candles/Sticker",
    170: "Handmade/Ceramics and Pottery/Bowls",
    171: "Handmade/Ceramics and Pottery/Home Decor",
    172: "Handmade/Ceramics and Pottery/Jewelry",
    173: "Handmade/Ceramics and Pottery/Kitchen",
    174: "Handmade/Ceramics and Pottery/Miniature",
    175: "Handmade/Ceramics and Pottery/Other",
    176: "Handmade/Ceramics and Pottery/Planters",
    177: "Handmade/Ceramics and Pottery/Sculptures",
    178: "Handmade/Ceramics and Pottery/Supplies",
    179: "Handmade/Children/Accessories",
    180: "Handmade/Children/Art",
    181: "Handmade/Children/Baby",
    182: "Handmade/Children/Clothing",
    183: "Handmade/Children/Jewelry",
    184: "Handmade/Children/Other",
    185: "Handmade/Children/Toddler",
    186: "Handmade/Children/Toy",
    187: "Handmade/Clothing/Children",
    188: "Handmade/Clothing/Corset",
    189: "Handmade/Clothing/Costume",
    190: "Handmade/Clothing/Dress",
    191: "Handmade/Clothing/Lingerie",
    192: "Handmade/Clothing/Other",
    193: "Handmade/Clothing/Shirt",
    194: "Handmade/Clothing/Shoes",
    195: "Handmade/Clothing/Tshirt",
    196: "Handmade/Clothing/Women",
    197: "Handmade/Crochet/Accessories",
    198: "Handmade/Crochet/Afghan",
    199: "Handmade/Crochet/Bags and Purses",
    200: "Handmade/Crochet/Clothing",
    201: "Handmade/Crochet/Doll",
    202: "Handmade/Crochet/Hat",
    203: "Handmade/Crochet/Housewares",
    204: "Handmade/Crochet/Jewelry",
    205: "Handmade/Crochet/Other",
    206: "Handmade/Crochet/Scarf",
    207: "Handmade/Crochet/Supplies",
    208: "Handmade/Dolls and Miniatures/Amigurumi",
    209: "Handmade/Dolls and Miniatures/Art Doll",
    210: "Handmade/Dolls and Miniatures/Fantasy",
    211: "Handmade/Dolls and Miniatures/Figurines",
    212: "Handmade/Dolls and Miniatures/Human Figure Doll",
    213: "Handmade/Dolls and Miniatures/Miniature",
    214: "Handmade/Dolls and Miniatures/Plush",
    215: "Handmade/Dolls and Miniatures/Primitive",
    216: "Handmade/Dolls and Miniatures/Scale Dollhouse Miniature",
    217: "Handmade/Dolls and Miniatures/Scale Models",
    218: "Handmade/Furniture/Chair",
    219: "Handmade/Furniture/Other",
    220: "Handmade/Geekery/Accessory",
    221: "Handmade/Geekery/Computer",
    222: "Handmade/Geekery/Fantasy",
    223: "Handmade/Geekery/Gadget",
    224: "Handmade/Geekery/Horror",
    225: "Handmade/Geekery/Humor",
    226: "Handmade/Geekery/Magic",
    227: "Handmade/Geekery/Other",
    228: "Handmade/Geekery/Science",
    229: "Handmade/Geekery/Toy",
    230: "Handmade/Geekery/Videogame",
    231: "Handmade/Glass/Beads",
    232: "Handmade/Glass/Bottles",
    233: "Handmade/Glass/Bowls",
    234: "Handmade/Glass/Dishes",
    235: "Handmade/Glass/Glassware",
    236: "Handmade/Glass/Home Decor",
    237: "Handmade/Glass/Ornaments",
    238: "Handmade/Glass/Other",
    239: "Handmade/Glass/Sculptures",
    240: "Handmade/Glass/Stained Glass",
    241: "Handmade/Glass/Supplies",
    242: "Handmade/Glass/Vases",
    243: "Handmade/Holidays/Birthday",
    244: "Handmade/Holidays/Christmas",
    245: "Handmade/Holidays/Easter",
    246: "Handmade/Holidays/Halloween",
    247: "Handmade/Holidays/New Years",
    248: "Handmade/Holidays/Other",
    249: "Handmade/Holidays/Thanksgiving",
    250: "Handmade/Holidays/Valentine",
    251: "Handmade/Housewares/Bedroom",
    252: "Handmade/Housewares/Cleaning",
    253: "Handmade/Housewares/Entertaining/Serving",
    254: "Handmade/Housewares/Home Decor",
    255: "Handmade/Housewares/Kitchen",
    256: "Handmade/Housewares/Lighting",
    257: "Handmade/Housewares/Magnets",
    258: "Handmade/Housewares/Office",
    259: "Handmade/Housewares/Other",
    260: "Handmade/Housewares/Outdoor",
    261: "Handmade/Housewares/Pillows",
    262: "Handmade/Housewares/Rugs",
    263: "Handmade/Housewares/Wall Decor",
    264: "Handmade/Jewelry/Books and Zines",
    265: "Handmade/Jewelry/Jewelry",
    266: "Handmade/Jewelry/Music",
    267: "Handmade/Jewelry/Other",
    268: "Handmade/Knitting/Accessories",
    269: "Handmade/Knitting/Blanket",
    270: "Handmade/Knitting/Hat",
    271: "Handmade/Knitting/Knitting Supplies",
    272: "Handmade/Knitting/Other",
    273: "Handmade/Knitting/Scarf",
    274: "Handmade/Music/Equipment",
    275: "Handmade/Music/Instrument",
    276: "Handmade/Music/Other",
    277: "Handmade/Music/Poster",
    278: "Handmade/Music/Tape",
    279: "Handmade/Music/Vinyl",
    280: "Handmade/Needlecraft/Accessories",
    281: "Handmade/Needlecraft/Clothing",
    282: "Handmade/Needlecraft/Cross Stitch",
    283: "Handmade/Needlecraft/Embroidery",
    284: "Handmade/Needlecraft/Felted",
    285: "Handmade/Needlecraft/Needlepoint",
    286: "Handmade/Needlecraft/Other",
    287: "Handmade/Needlecraft/Pattern",
    288: "Handmade/Needlecraft/Pillow",
    289: "Handmade/Needlecraft/Supplies",
    290: "Handmade/Other/Other",
    291: "Handmade/Others/Custom",
    292: "Handmade/Others/Educational",
    293: "Handmade/Others/Graphic Design",
    294: "Handmade/Others/Magic",
    295: "Handmade/Others/Other",
    296: "Handmade/Others/Personalized",
    297: "Handmade/Others/Religious",
    298: "Handmade/Paper Goods/Bookmark",
    299: "Handmade/Paper Goods/Calendar",
    300: "Handmade/Paper Goods/Cards",
    301: "Handmade/Paper Goods/Gift Wrap",
    302: "Handmade/Paper Goods/Journal",
    303: "Handmade/Paper Goods/Notebook",
    304: "Handmade/Paper Goods/Origami",
    305: "Handmade/Paper Goods/Other",
    306: "Handmade/Paper Goods/Papermaking",
    307: "Handmade/Paper Goods/Scrapbooking",
    308: "Handmade/Paper Goods/Stationery",
    309: "Handmade/Paper Goods/Sticker",
    310: "Handmade/Paper Goods/Tag",
    311: "Handmade/Patterns/Accessories",
    312: "Handmade/Patterns/Beading",
    313: "Handmade/Patterns/Crochet",
    314: "Handmade/Patterns/Handmade",
    315: "Handmade/Patterns/Home",
    316: "Handmade/Patterns/Knitting",
    317: "Handmade/Patterns/Other",
    318: "Handmade/Patterns/Painting",
    319: "Handmade/Patterns/Quilt",
    320: "Handmade/Patterns/Sewing",
    321: "Handmade/Pets/Accessories",
    322: "Handmade/Pets/Bed",
    323: "Handmade/Pets/Blanket",
    324: "Handmade/Pets/Bowl",
    325: "Handmade/Pets/Clothing",
    326: "Handmade/Pets/Collar",
    327: "Handmade/Pets/Feeding",
    328: "Handmade/Pets/Grooming",
    329: "Handmade/Pets/Leash",
    330: "Handmade/Pets/Other",
    331: "Handmade/Pets/Pet Lover",
    332: "Handmade/Pets/Small Animal",
    333: "Handmade/Pets/Toy",
    334: "Handmade/Quilts/Baby",
    335: "Handmade/Quilts/Bed",
    336: "Handmade/Quilts/Other",
    337: "Handmade/Quilts/Patch",
    338: "Handmade/Quilts/Patchwork",
    339: "Handmade/Toys/Baby",
    340: "Handmade/Toys/Children",
    341: "Handmade/Toys/Doll",
    342: "Handmade/Toys/Food",
    343: "Handmade/Toys/Game",
    344: "Handmade/Toys/Other",
    345: "Handmade/Toys/Plush",
    346: "Handmade/Toys/Pretend",
    347: "Handmade/Weddings/Accessories",
    348: "Handmade/Weddings/Bouquets",
    349: "Handmade/Weddings/Cake Toppers",
    350: "Handmade/Weddings/Cards",
    351: "Handmade/Weddings/Clothing",
    352: "Handmade/Weddings/Decorations",
    353: "Handmade/Weddings/Favors",
    354: "Handmade/Weddings/Frames",
    355: "Handmade/Weddings/Guest Books",
    356: "Handmade/Weddings/Invitations",
    357: "Handmade/Weddings/Jewelry",
    358: "Handmade/Weddings/Just Married",
    359: "Handmade/Weddings/Men",
    360: "Handmade/Weddings/Other",
    361: "Handmade/Weddings/Pillows",
    362: "Handmade/Weddings/Portraits",
    363: "Handmade/Woodworking/Accessories",
    364: "Handmade/Woodworking/Boxes",
    365: "Handmade/Woodworking/Burning",
    366: "Handmade/Woodworking/Carving",
    367: "Handmade/Woodworking/Home Decor",
    368: "Handmade/Woodworking/Jewelry",
    369: "Handmade/Woodworking/Miniature",
    370: "Handmade/Woodworking/Other",
    371: "Handmade/Woodworking/Seasonal",
    372: "Handmade/Woodworking/Signs",
    373: "Handmade/Woodworking/Supplies",
    374: "Handmade/Woodworking/Toys",
    375: "Home/Artwork/Drawings",
    376: "Home/Artwork/Lithographs, Etchings & Woodcuts",
    377: "Home/Artwork/Other",
    378: "Home/Artwork/Paintings",
    379: "Home/Artwork/Photographs",
    380: "Home/Artwork/Posters & Prints",
    381: "Home/Bath/Bath Linen Sets",
    382: "Home/Bath/Bath Rugs",
    383: "Home/Bath/Bathroom Accessories",
    384: "Home/Bath/Bathroom Furniture Sets",
    385: "Home/Bath/Bathroom Shelves",
    386: "Home/Bath/Other",
    387: "Home/Bath/Towels",
    388: "Home/Bedding/Bed in a Bag",
    389: "Home/Bedding/Bed Pillows",
    390: "Home/Bedding/Bedspreads & Coverlets",
    391: "Home/Bedding/Blankets & Throws",
    392: "Home/Bedding/Comforters & Sets",
    393: "Home/Bedding/Decorative Pillows, Inserts & Covers",
    394: "Home/Bedding/Duvet Covers & Sets",
    395: "Home/Bedding/Inflatable Beds",
    396: "Home/Bedding/Mattress Pads",
    397: "Home/Bedding/Other",
    398: "Home/Bedding/Quilts",
    399: "Home/Bedding/Shams, Bed Skirts & Bed Frame Draperies",
    400: "Home/Bedding/Sheets & Pillowcases",
    401: "Home/Cleaning Supplies/Air Fresheners",
    402: "Home/Cleaning Supplies/Brushes",
    403: "Home/Cleaning Supplies/Dusting",
    404: "Home/Cleaning Supplies/Gloves",
    405: "Home/Cleaning Supplies/Household Cleaners",
    406: "Home/Cleaning Supplies/Mopping",
    407: "Home/Cleaning Supplies/Other",
    408: "Home/Cleaning Supplies/Paper Towels",
    409: "Home/Cleaning Supplies/Sponges",
    410: "Home/Cleaning Supplies/Sweeping",
    411: "Home/Cleaning Supplies/Trash Bags",
    412: "Home/Furniture/Bathroom Furniture",
    413: "Home/Furniture/Bedroom Furniture",
    414: "Home/Furniture/Home Bar Furniture",
    415: "Home/Furniture/Home Entertainment Furniture",
    416: "Home/Furniture/Home Office Furniture",
    417: "Home/Furniture/Living Room Furniture",
    418: "Home/Furniture/Other",
    419: "Home/Furniture/Other Furniture",
    420: "Home/Furniture/Replacement Parts",
    421: "Home/Home Appliances/Air Conditioners",
    422: "Home/Home Appliances/Air Purifiers",
    423: "Home/Home Appliances/Dehumidifiers",
    424: "Home/Home Appliances/Fans",
    425: "Home/Home Appliances/Freezers & Ice Makers",
    426: "Home/Home Appliances/Garbage Disposals",
    427: "Home/Home Appliances/Garment Steamers",
    428: "Home/Home Appliances/Humidifiers",
    429: "Home/Home Appliances/Irons & Ironing Boards",
    430: "Home/Home Appliances/Kitchen Appliances",
    431: "Home/Home Appliances/Microwaves",
    432: "Home/Home Appliances/Refrigerators",
    433: "Home/Home Appliances/Space Heaters",
    434: "Home/Home Appliances/Vacuums & Floor Care",
    435: "Home/Home Appliances/Washers & Dryers",
    436: "Home/Home Appliances/Water Coolers & Filters",
    437: "Home/Home Appliances/Wine, Beer & Beverage Coolers",
    438: "Home/Home DГ©cor/Area Rugs & Pads",
    439: "Home/Home DГ©cor/Baskets",
    440: "Home/Home DГ©cor/Candles & Holders",
    441: "Home/Home DГ©cor/Clocks",
    442: "Home/Home DГ©cor/Decorative Pillows",
    443: "Home/Home DГ©cor/Doormats",
    444: "Home/Home DГ©cor/Home DГ©cor Accents",
    445: "Home/Home DГ©cor/Home Fragrance",
    446: "Home/Home DГ©cor/Lamps& Accessories",
    447: "Home/Home DГ©cor/Mirrors",
    448: "Home/Home DГ©cor/Other",
    449: "Home/Home DГ©cor/Photo Albums & Frames",
    450: "Home/Home DГ©cor/Slipcovers",
    451: "Home/Home DГ©cor/Tapestries",
    452: "Home/Home DГ©cor/Vases",
    453: "Home/Home DГ©cor/Window Treatments",
    454: "Home/Kids' Home Store/Kids' Bath",
    455: "Home/Kids' Home Store/Kids' Bedding",
    456: "Home/Kids' Home Store/Kids' Flatware",
    457: "Home/Kids' Home Store/Kids' Furniture",
    458: "Home/Kids' Home Store/Kids' Room DГ©cor",
    459: "Home/Kids' Home Store/Nursery Bedding",
    460: "Home/Kids' Home Store/Nursery DГ©cor",
    461: "Home/Kids' Home Store/Nursery Furniture",
    462: "Home/Kids' Home Store/Other",
    463: "Home/Kitchen & Dining/Bakeware",
    464: "Home/Kitchen & Dining/Coffee & Tea Accessories",
    465: "Home/Kitchen & Dining/Cookware",
    466: "Home/Kitchen & Dining/Dining & Entertaining",
    467: "Home/Kitchen & Dining/Food Service Equipment & Supplies",
    468: "Home/Kitchen & Dining/Home Brewing & Wine Making",
    469: "Home/Kitchen & Dining/Kitchen & Table Linens",
    470: "Home/Kitchen & Dining/Kitchen Knives & Cutlery Accessories",
    471: "Home/Kitchen & Dining/Kitchen Utensils & Gadgets",
    472: "Home/Kitchen & Dining/Other",
    473: "Home/Kitchen & Dining/Small Appliances",
    474: "Home/Kitchen & Dining/Storage & Organization",
    475: "Home/Kitchen & Dining/Water Coolers & Filters",
    476: "Home/Kitchen & Dining/Wine Accessories",
    477: "Home/Other/Other",
    478: "Home/Seasonal DГ©cor/Birthday",
    479: "Home/Seasonal DГ©cor/Christmas",
    480: "Home/Seasonal DГ©cor/Day of the Dead",
    481: "Home/Seasonal DГ©cor/Easter",
    482: "Home/Seasonal DГ©cor/Halloween",
    483: "Home/Seasonal DГ©cor/New Year's",
    484: "Home/Seasonal DГ©cor/Other",
    485: "Home/Seasonal DГ©cor/Patriotic",
    486: "Home/Seasonal DГ©cor/St Patrick's",
    487: "Home/Seasonal DГ©cor/Thanksgiving",
    488: "Home/Seasonal DГ©cor/Valentine",
    489: "Home/Storage & Organization/Baskets & Bins",
    490: "Home/Storage & Organization/Bathroom Storage & Organization",
    491: "Home/Storage & Organization/Clothing & Closet Storage",
    492: "Home/Storage & Organization/Garage Storage & Organization",
    493: "Home/Storage & Organization/Jewelry Boxes & Organizers",
    494: "Home/Storage & Organization/Kitchen Storage & Organization",
    495: "Home/Storage & Organization/Laundry Storage & Organization",
    496: "Home/Storage & Organization/Other",
    497: "Home/Storage & Organization/Racks, Shelves & Drawers",
    498: "Home/Storage & Organization/Storage Cabinets",
    499: "Home/Storage & Organization/Trash & Recycling",
    500: "Kids/Bathing & Skin Care/Bathing Tubs & Seats",
    501: "Kids/Bathing & Skin Care/Bathroom Safety",
    502: "Kids/Bathing & Skin Care/Bubble Bath",
    503: "Kids/Bathing & Skin Care/Conditioners",
    504: "Kids/Bathing & Skin Care/Grooming & Healthcare Kits",
    505: "Kids/Bathing & Skin Care/Other",
    506: "Kids/Bathing & Skin Care/Shampoo",
    507: "Kids/Bathing & Skin Care/Skin Care",
    508: "Kids/Bathing & Skin Care/Soaps & Cleansers",
    509: "Kids/Bathing & Skin Care/Travel Bathing Kits",
    510: "Kids/Bathing & Skin Care/Washcloths & Towels",
    511: "Kids/Boys (4+)/Accessories",
    512: "Kids/Boys (4+)/Bottoms",
    513: "Kids/Boys (4+)/Coats & Jackets",
    514: "Kids/Boys (4+)/Other",
    515: "Kids/Boys (4+)/Shoes",
    516: "Kids/Boys (4+)/Swimwear",
    517: "Kids/Boys (4+)/Top & T-shirts",
    518: "Kids/Boys 0-24 Mos/Accessories",
    519: "Kids/Boys 0-24 Mos/Bottoms",
    520: "Kids/Boys 0-24 Mos/Coats & Jackets",
    521: "Kids/Boys 0-24 Mos/One-Pieces",
    522: "Kids/Boys 0-24 Mos/Other",
    523: "Kids/Boys 0-24 Mos/Shoes",
    524: "Kids/Boys 0-24 Mos/Swimwear",
    525: "Kids/Boys 0-24 Mos/Tops & T-Shirts",
    526: "Kids/Boys 2T-5T/Accessories",
    527: "Kids/Boys 2T-5T/Bottoms",
    528: "Kids/Boys 2T-5T/Coats & Jackets",
    529: "Kids/Boys 2T-5T/One-Pieces",
    530: "Kids/Boys 2T-5T/Other",
    531: "Kids/Boys 2T-5T/Shoes",
    532: "Kids/Boys 2T-5T/Swimwear",
    533: "Kids/Boys 2T-5T/Tops & T-Shirts",
    534: "Kids/Car Seats & Accessories/Accessories",
    535: "Kids/Car Seats & Accessories/Car Seats",
    536: "Kids/Car Seats & Accessories/Other",
    537: "Kids/Diapering/Changing Kits",
    538: "Kids/Diapering/Changing Pads & Covers",
    539: "Kids/Diapering/Cloth Diapers",
    540: "Kids/Diapering/Diaper Bags",
    541: "Kids/Diapering/Diaper Pails & Refills",
    542: "Kids/Diapering/Diaper Stackers & Caddies",
    543: "Kids/Diapering/Disposable Diapers",
    544: "Kids/Diapering/Other",
    545: "Kids/Diapering/Powders & Lotions",
    546: "Kids/Diapering/Washcloths & Towels",
    547: "Kids/Diapering/Wipes & Holders",
    548: "Kids/Feeding/Bottle-Feeding",
    549: "Kids/Feeding/Breastfeeding",
    550: "Kids/Feeding/Gift Sets",
    551: "Kids/Feeding/Highchairs & Booster Seats",
    552: "Kids/Feeding/Other",
    553: "Kids/Feeding/Pacifiers & Accessories",
    554: "Kids/Feeding/Pillows & Stools",
    555: "Kids/Feeding/Storage & Containers",
    556: "Kids/Gear/Activity Centers & Entertainers",
    557: "Kids/Gear/Baby Gyms & Playmats",
    558: "Kids/Gear/Baby Seats",
    559: "Kids/Gear/Backpacks & Carriers",
    560: "Kids/Gear/Harnesses & Leashes",
    561: "Kids/Gear/Other",
    562: "Kids/Gear/Playard Bedding",
    563: "Kids/Gear/Playards",
    564: "Kids/Gear/Shopping Cart Covers",
    565: "Kids/Gear/Swings, Jumpers & Bouncers",
    566: "Kids/Gear/Travel Beds",
    567: "Kids/Gear/Walkers",
    568: "Kids/Girls (4+)/Accessories",
    569: "Kids/Girls (4+)/Coats & Jackets",
    570: "Kids/Girls (4+)/Dresses",
    571: "Kids/Girls (4+)/Jeans",
    572: "Kids/Girls (4+)/Other",
    573: "Kids/Girls (4+)/Shoes",
    574: "Kids/Girls (4+)/Swimwear",
    575: "Kids/Girls (4+)/Tops & T-Shirts",
    576: "Kids/Girls 0-24 Mos/Accessories",
    577: "Kids/Girls 0-24 Mos/Bottoms",
    578: "Kids/Girls 0-24 Mos/Coats & Jackets",
    579: "Kids/Girls 0-24 Mos/Dresses",
    580: "Kids/Girls 0-24 Mos/One-Pieces",
    581: "Kids/Girls 0-24 Mos/Other",
    582: "Kids/Girls 0-24 Mos/Shoes",
    583: "Kids/Girls 0-24 Mos/Swimwear",
    584: "Kids/Girls 0-24 Mos/Tops & T-Shirts",
    585: "Kids/Girls 2T-5T/Accessories",
    586: "Kids/Girls 2T-5T/Bottoms",
    587: "Kids/Girls 2T-5T/Coats & Jackets",
    588: "Kids/Girls 2T-5T/Dresses",
    589: "Kids/Girls 2T-5T/One-Pieces",
    590: "Kids/Girls 2T-5T/Other",
    591: "Kids/Girls 2T-5T/Shoes",
    592: "Kids/Girls 2T-5T/Swimwear",
    593: "Kids/Girls 2T-5T/Tops & T-Shirts",
    594: "Kids/Health & Baby Care/Humidifiers & Vaporizers",
    595: "Kids/Health & Baby Care/Nail Care",
    596: "Kids/Health & Baby Care/Nasal Aspirators",
    597: "Kids/Health & Baby Care/Other",
    598: "Kids/Health & Baby Care/Sun Protection",
    599: "Kids/Health & Baby Care/Teethers",
    600: "Kids/Health & Baby Care/Teething Relief",
    601: "Kids/Health & Baby Care/Thermometers",
    602: "Kids/Health & Baby Care/Toothbrushes",
    603: "Kids/Nursery/Bedding",
    604: "Kids/Nursery/Furniture",
    605: "Kids/Nursery/Nursery DГ©cor",
    606: "Kids/Nursery/Other",
    607: "Kids/Other/Other",
    608: "Kids/Potty Training/Potties & Seats",
    609: "Kids/Potty Training/Seat Covers",
    610: "Kids/Potty Training/Step Stools",
    611: "Kids/Potty Training/Training Pants",
    612: "Kids/Pregnancy & Maternity/Breastfeeding Pillows & Stools",
    613: "Kids/Pregnancy & Maternity/Family Planning Tests",
    614: "Kids/Pregnancy & Maternity/Maternity Pillows",
    615: "Kids/Pregnancy & Maternity/Other",
    616: "Kids/Pregnancy & Maternity/Prenatal Monitoring Devices",
    617: "Kids/Safety/Bathroom Safety",
    618: "Kids/Safety/Cabinet Locks & Straps",
    619: "Kids/Safety/Electrical Safety",
    620: "Kids/Safety/Gates & Doorways",
    621: "Kids/Safety/Harnesses & Leashes",
    622: "Kids/Safety/Kitchen Safety",
    623: "Kids/Safety/Monitors",
    624: "Kids/Safety/Other",
    625: "Kids/Safety/Outdoor Safety",
    626: "Kids/Safety/Rails & Rail Guards",
    627: "Kids/Safety/Sleep Positioners",
    628: "Kids/Strollers/Accessories",
    629: "Kids/Strollers/Joggers",
    630: "Kids/Strollers/Lightweight",
    631: "Kids/Strollers/Other",
    632: "Kids/Strollers/Prams",
    633: "Kids/Strollers/Standard",
    634: "Kids/Strollers/Tandem",
    635: "Kids/Strollers/Travel Systems",
    636: "Kids/Toys/Action Figures & Statues",
    637: "Kids/Toys/Arts & Crafts",
    638: "Kids/Toys/Baby & Toddler Toys",
    639: "Kids/Toys/Building Toys",
    640: "Kids/Toys/Dolls & Accessories",
    641: "Kids/Toys/Dress Up & Pretend Play",
    642: "Kids/Toys/Electronics for Kids",
    643: "Kids/Toys/Games",
    644: "Kids/Toys/Hobbies",
    645: "Kids/Toys/Kids' Furniture, DГ©cor & Storage",
    646: "Kids/Toys/Learning & Education",
    647: "Kids/Toys/Novelty & Gag Toys",
    648: "Kids/Toys/Other",
    649: "Kids/Toys/Party Supplies",
    650: "Kids/Toys/Puzzles",
    651: "Kids/Toys/Sports & Outdoor Play",
    652: "Kids/Toys/Stuffed Animals & Plush",
    653: "Kids/Toys/Toy Remote Control & Play Vehicles",
    654: "Kids/Toys/Tricycles, Scooters & Wagons",
    655: "Men/Athletic Apparel/Jackets",
    656: "Men/Athletic Apparel/Jerseys",
    657: "Men/Athletic Apparel/Other",
    658: "Men/Athletic Apparel/Pants",
    659: "Men/Athletic Apparel/Shirts & Tops",
    660: "Men/Athletic Apparel/Shorts",
    661: "Men/Athletic Apparel/Snowsuits & Bibs",
    662: "Men/Athletic Apparel/Socks",
    663: "Men/Athletic Apparel/Tracksuits & Sweats",
    664: "Men/Athletic Apparel/Vests",
    665: "Men/Blazers & Sport Coats/Double Breasted",
    666: "Men/Blazers & Sport Coats/One Button",
    667: "Men/Blazers & Sport Coats/Other",
    668: "Men/Blazers & Sport Coats/Three Button",
    669: "Men/Blazers & Sport Coats/Two Button",
    670: "Men/Coats & Jackets/Fleece Jacket",
    671: "Men/Coats & Jackets/Flight/Bomber",
    672: "Men/Coats & Jackets/Jean Jacket",
    673: "Men/Coats & Jackets/Military",
    674: "Men/Coats & Jackets/Motorcycle",
    675: "Men/Coats & Jackets/Other",
    676: "Men/Coats & Jackets/Parka",
    677: "Men/Coats & Jackets/Peacoat",
    678: "Men/Coats & Jackets/Poncho",
    679: "Men/Coats & Jackets/Puffer",
    680: "Men/Coats & Jackets/Rainwear",
    681: "Men/Coats & Jackets/Trench",
    682: "Men/Coats & Jackets/Varsity/Baseball",
    683: "Men/Coats & Jackets/Vest",
    684: "Men/Coats & Jackets/Windbreaker",
    685: "Men/Coats & Jackets/Wool",
    686: "Men/Jeans/Baggy, Loose",
    687: "Men/Jeans/Boot Cut",
    688: "Men/Jeans/Cargo",
    689: "Men/Jeans/Carpenter",
    690: "Men/Jeans/Classic, Straight Leg",
    691: "Men/Jeans/Other",
    692: "Men/Jeans/Overalls",
    693: "Men/Jeans/Relaxed",
    694: "Men/Jeans/Slim, Skinny",
    695: "Men/Men's Accessories/Backpacks, Bags & Briefcases",
    696: "Men/Men's Accessories/Belts",
    697: "Men/Men's Accessories/Hats",
    698: "Men/Men's Accessories/Other",
    699: "Men/Men's Accessories/Sunglasses",
    700: "Men/Men's Accessories/Ties",
    701: "Men/Men's Accessories/Wallets",
    702: "Men/Men's Accessories/Watches",
    703: "Men/Other/Other",
    704: "Men/Pants/Cargo",
    705: "Men/Pants/Carpenter",
    706: "Men/Pants/Casual Pants",
    707: "Men/Pants/Corduroys",
    708: "Men/Pants/Dress - Flat Front",
    709: "Men/Pants/Dress - Pleat",
    710: "Men/Pants/Khakis, Chinos",
    711: "Men/Pants/Other",
    712: "Men/Shoes/Athletic",
    713: "Men/Shoes/Boots",
    714: "Men/Shoes/Fashion Sneakers",
    715: "Men/Shoes/Loafers & Slip-Ons",
    716: "Men/Shoes/Mules & Clogs",
    717: "Men/Shoes/Outdoor",
    718: "Men/Shoes/Oxfords",
    719: "Men/Shoes/Sandals",
    720: "Men/Shoes/Slippers",
    721: "Men/Shoes/Work & Safety",
    722: "Men/Shorts/Athletic",
    723: "Men/Shorts/Board, Surf",
    724: "Men/Shorts/Cargo",
    725: "Men/Shorts/Carpenter, Utility",
    726: "Men/Shorts/Casual Shorts",
    727: "Men/Shorts/Corduroys",
    728: "Men/Shorts/Denim",
    729: "Men/Shorts/Dress Shorts",
    730: "Men/Shorts/Khakis, Chinos",
    731: "Men/Shorts/Other",
    732: "Men/Suits/Four Button",
    733: "Men/Suits/One Button",
    734: "Men/Suits/Other",
    735: "Men/Suits/Three Button",
    736: "Men/Suits/Tuxedo",
    737: "Men/Suits/Two Button",
    738: "Men/Sweaters/Cardigan",
    739: "Men/Sweaters/Crewneck",
    740: "Men/Sweaters/Full Zip",
    741: "Men/Sweaters/Other",
    742: "Men/Sweaters/Polo",
    743: "Men/Sweaters/Turtleneck",
    744: "Men/Sweaters/Vest",
    745: "Men/Sweaters/V-Neck",
    746: "Men/Sweats & Hoodies/Hoodie",
    747: "Men/Sweats & Hoodies/Other",
    748: "Men/Sweats & Hoodies/Sweatshirt, Pullover",
    749: "Men/Sweats & Hoodies/Track & Sweat Pants",
    750: "Men/Sweats & Hoodies/Track & Sweat Suits",
    751: "Men/Sweats & Hoodies/Track Jacket",
    752: "Men/Swimwear/Board Shorts",
    753: "Men/Swimwear/Swim Briefs",
    754: "Men/Swimwear/Swim Trunks",
    755: "Men/Tops/Button-Front",
    756: "Men/Tops/Dress Shirts",
    757: "Men/Tops/Hawaiian",
    758: "Men/Tops/Henley",
    759: "Men/Tops/Other",
    760: "Men/Tops/Polo, Rugby",
    761: "Men/Tops/Tank",
    762: "Men/Tops/T-shirts",
    763: "Men/Tops/Turtleneck",
    764: "Other/Automotive/Automotive Enthusiast Merchandise",
    765: "Other/Automotive/Car Care",
    766: "Other/Automotive/Car Electronics & Accessories",
    767: "Other/Automotive/Exterior Accessories",
    768: "Other/Automotive/Interior Accessories",
    769: "Other/Automotive/Lights & Lighting Accessories",
    770: "Other/Automotive/Motorcycle & Powersports",
    771: "Other/Automotive/Oils & Fluids",
    772: "Other/Automotive/Other",
    773: "Other/Automotive/Paint, Body & Trim",
    774: "Other/Automotive/Performance Parts & Accessories",
    775: "Other/Automotive/Replacement Parts",
    776: "Other/Automotive/Tires & Wheels",
    777: "Other/Automotive/Tools & Equipment",
    778: "Other/Books/Arts & Photography",
    779: "Other/Books/Biographies & Memoirs",
    780: "Other/Books/Business & Money",
    781: "Other/Books/Children's Books",
    782: "Other/Books/Christian Books & Bibles",
    783: "Other/Books/Education & Teaching",
    784: "Other/Books/History",
    785: "Other/Books/Literature & Fiction",
    786: "Other/Books/Medical Books",
    787: "Other/Books/Other",
    788: "Other/Books/Politics & Social Sciences",
    789: "Other/Books/Reference",
    790: "Other/Books/Religion & Spirituality",
    791: "Other/Books/Science & Math",
    792: "Other/Daily & Travel items/Baby & Child Care",
    793: "Other/Daily & Travel items/Health Care",
    794: "Other/Daily & Travel items/Household Supplies",
    795: "Other/Daily & Travel items/Medical Supplies & Equipment",
    796: "Other/Daily & Travel items/Other",
    797: "Other/Daily & Travel items/Personal Care",
    798: "Other/Daily & Travel items/Sports Nutrition",
    799: "Other/Daily & Travel items/Stationery & Party Supplies",
    800: "Other/Magazines/Lifestyle & Cultures",
    801: "Other/Magazines/Other",
    802: "Other/Magazines/Professional & Trade",
    803: "Other/Musical instruments/Amplifiers & Effects",
    804: "Other/Musical instruments/Band & Orchestra",
    805: "Other/Musical instruments/Brass Instruments",
    806: "Other/Musical instruments/DJ, Electronic Music & Karaoke",
    807: "Other/Musical instruments/Drums & Percussion",
    808: "Other/Musical instruments/Guitars",
    809: "Other/Musical instruments/Instrument Accessories",
    810: "Other/Musical instruments/Keyboards",
    811: "Other/Musical instruments/Microphones & Accessories",
    812: "Other/Musical instruments/Other",
    813: "Other/Musical instruments/Stringed Instruments",
    814: "Other/Musical instruments/Studio Recording Equipment",
    815: "Other/Musical instruments/Wind & Woodwind Instruments",
    816: "Other/Office supplies/Basic Supplies",
    817: "Other/Office supplies/Calendars",
    818: "Other/Office supplies/Electronics",
    819: "Other/Office supplies/Furniture",
    820: "Other/Office supplies/Ink & Toner",
    821: "Other/Office supplies/Organization",
    822: "Other/Office supplies/Other",
    823: "Other/Office supplies/Paper",
    824: "Other/Office supplies/Presentation",
    825: "Other/Office supplies/School Supplies",
    826: "Other/Office supplies/Shipping Supplies",
    827: "Other/Office supplies/Writing",
    828: "Other/Other/Other",
    829: "Other/Pet Supplies/Cage",
    830: "Other/Pet Supplies/Dogs",
    831: "Other/Pet Supplies/Others",
    832: "Sports & Outdoors/Apparel/Accessories",
    833: "Sports & Outdoors/Apparel/Boys",
    834: "Sports & Outdoors/Apparel/Girls",
    835: "Sports & Outdoors/Apparel/Men",
    836: "Sports & Outdoors/Apparel/Other",
    837: "Sports & Outdoors/Apparel/Women",
    838: "Sports & Outdoors/Exercise/Athletic Training",
    839: "Sports & Outdoors/Exercise/Bowling",
    840: "Sports & Outdoors/Exercise/Boxing & MMA",
    841: "Sports & Outdoors/Exercise/Dance/Ballet",
    842: "Sports & Outdoors/Exercise/Fitness accessories",
    843: "Sports & Outdoors/Exercise/Fitness technology",
    844: "Sports & Outdoors/Exercise/Other",
    845: "Sports & Outdoors/Exercise/Strength training",
    846: "Sports & Outdoors/Exercise/Track & Field",
    847: "Sports & Outdoors/Exercise/Yoga & Pilates",
    848: "Sports & Outdoors/Fan Shop/MLB",
    849: "Sports & Outdoors/Fan Shop/NBA",
    850: "Sports & Outdoors/Fan Shop/NCAA",
    851: "Sports & Outdoors/Fan Shop/NFL",
    852: "Sports & Outdoors/Fan Shop/NHL",
    853: "Sports & Outdoors/Fan Shop/Other",
    854: "Sports & Outdoors/Footwear/Cleats",
    855: "Sports & Outdoors/Footwear/Kids",
    856: "Sports & Outdoors/Footwear/Men",
    857: "Sports & Outdoors/Footwear/Other",
    858: "Sports & Outdoors/Footwear/Women",
    859: "Sports & Outdoors/Golf/Electronics",
    860: "Sports & Outdoors/Golf/Golf Apparel",
    861: "Sports & Outdoors/Golf/Golf Bags",
    862: "Sports & Outdoors/Golf/Golf Balls",
    863: "Sports & Outdoors/Golf/Golf Shoes",
    864: "Sports & Outdoors/Golf/Men's Golf Clubs",
    865: "Sports & Outdoors/Golf/Other",
    866: "Sports & Outdoors/Golf/Women's Golf Clubs",
    867: "Sports & Outdoors/Other/Other",
    868: "Sports & Outdoors/Outdoors/Bike & Skate",
    869: "Sports & Outdoors/Outdoors/Boating",
    870: "Sports & Outdoors/Outdoors/Fishing",
    871: "Sports & Outdoors/Outdoors/Hiking & Camping",
    872: "Sports & Outdoors/Outdoors/Indoor/Outdoor Games",
    873: "Sports & Outdoors/Outdoors/Other",
    874: "Sports & Outdoors/Outdoors/Skateboard",
    875: "Sports & Outdoors/Outdoors/Snowboard",
    876: "Sports & Outdoors/Outdoors/Water Sports",
    877: "Sports & Outdoors/Team Sports/All Other Sports",
    878: "Sports & Outdoors/Team Sports/Badminton",
    879: "Sports & Outdoors/Team Sports/Baseball & Softball",
    880: "Sports & Outdoors/Team Sports/Basketball",
    881: "Sports & Outdoors/Team Sports/Football",
    882: "Sports & Outdoors/Team Sports/Hockey",
    883: "Sports & Outdoors/Team Sports/Lacrosse",
    884: "Sports & Outdoors/Team Sports/Soccer",
    885: "Sports & Outdoors/Team Sports/Tennis & Racquets",
    886: "Sports & Outdoors/Team Sports/Volleyball",
    887: "Vintage & Collectibles/Accessories/Apron",
    888: "Vintage & Collectibles/Accessories/Belt",
    889: "Vintage & Collectibles/Accessories/Brooch",
    890: "Vintage & Collectibles/Accessories/Buckle",
    891: "Vintage & Collectibles/Accessories/Compact",
    892: "Vintage & Collectibles/Accessories/Cuff Links",
    893: "Vintage & Collectibles/Accessories/Eyewear",
    894: "Vintage & Collectibles/Accessories/Gloves",
    895: "Vintage & Collectibles/Accessories/Handkerchief",
    896: "Vintage & Collectibles/Accessories/Hat",
    897: "Vintage & Collectibles/Accessories/Keychain",
    898: "Vintage & Collectibles/Accessories/Other",
    899: "Vintage & Collectibles/Accessories/Scarf",
    900: "Vintage & Collectibles/Accessories/Shawl",
    901: "Vintage & Collectibles/Accessories/Shoes",
    902: "Vintage & Collectibles/Accessories/Wallet",
    903: "Vintage & Collectibles/Antique/100 Years or Older",
    904: "Vintage & Collectibles/Antique/50 To 75 Years",
    905: "Vintage & Collectibles/Antique/75 To 100 Years",
    906: "Vintage & Collectibles/Antique/Accessories",
    907: "Vintage & Collectibles/Antique/Bags and Purses",
    908: "Vintage & Collectibles/Antique/Book",
    909: "Vintage & Collectibles/Antique/Collectibles",
    910: "Vintage & Collectibles/Antique/Electronics",
    911: "Vintage & Collectibles/Antique/Home Decor",
    912: "Vintage & Collectibles/Antique/Housewares",
    913: "Vintage & Collectibles/Antique/Jewelry",
    914: "Vintage & Collectibles/Antique/Other",
    915: "Vintage & Collectibles/Antique/Paper Ephemera",
    916: "Vintage & Collectibles/Antique/Toy",
    917: "Vintage & Collectibles/Bags and Purses/Case",
    918: "Vintage & Collectibles/Bags and Purses/Change Purse",
    919: "Vintage & Collectibles/Bags and Purses/Clutch",
    920: "Vintage & Collectibles/Bags and Purses/Diaper Bag",
    921: "Vintage & Collectibles/Bags and Purses/Formal",
    922: "Vintage & Collectibles/Bags and Purses/Handbag",
    923: "Vintage & Collectibles/Bags and Purses/Leather",
    924: "Vintage & Collectibles/Bags and Purses/Luggage",
    925: "Vintage & Collectibles/Bags and Purses/Other",
    926: "Vintage & Collectibles/Bags and Purses/Pouch",
    927: "Vintage & Collectibles/Bags and Purses/Purse",
    928: "Vintage & Collectibles/Bags and Purses/Tote",
    929: "Vintage & Collectibles/Bags and Purses/Wallet",
    930: "Vintage & Collectibles/Book/Art",
    931: "Vintage & Collectibles/Book/Biography",
    932: "Vintage & Collectibles/Book/Children",
    933: "Vintage & Collectibles/Book/Comics",
    934: "Vintage & Collectibles/Book/Cookbook",
    935: "Vintage & Collectibles/Book/Crafting",
    936: "Vintage & Collectibles/Book/Decorating",
    937: "Vintage & Collectibles/Book/Fiction",
    938: "Vintage & Collectibles/Book/Health",
    939: "Vintage & Collectibles/Book/History",
    940: "Vintage & Collectibles/Book/How to",
    941: "Vintage & Collectibles/Book/Illustrated",
    942: "Vintage & Collectibles/Book/Instructional",
    943: "Vintage & Collectibles/Book/Nonfiction",
    944: "Vintage & Collectibles/Book/Other",
    945: "Vintage & Collectibles/Book/Poetry",
    946: "Vintage & Collectibles/Book/Reference",
    947: "Vintage & Collectibles/Book/Religion",
    948: "Vintage & Collectibles/Book/Science",
    949: "Vintage & Collectibles/Book/Scifi",
    950: "Vintage & Collectibles/Clothing/Baby",
    951: "Vintage & Collectibles/Clothing/Blouse",
    952: "Vintage & Collectibles/Clothing/Children",
    953: "Vintage & Collectibles/Clothing/Corset",
    954: "Vintage & Collectibles/Clothing/Dress",
    955: "Vintage & Collectibles/Clothing/Jacket",
    956: "Vintage & Collectibles/Clothing/Other",
    957: "Vintage & Collectibles/Clothing/Outerwear",
    958: "Vintage & Collectibles/Clothing/Pants",
    959: "Vintage & Collectibles/Clothing/Shawl",
    960: "Vintage & Collectibles/Clothing/Shirt",
    961: "Vintage & Collectibles/Clothing/Shorts",
    962: "Vintage & Collectibles/Clothing/Skirt",
    963: "Vintage & Collectibles/Clothing/Sweater",
    964: "Vintage & Collectibles/Clothing/Swimwear",
    965: "Vintage & Collectibles/Clothing/Tank",
    966: "Vintage & Collectibles/Clothing/Tshirt",
    967: "Vintage & Collectibles/Collectibles/Doll",
    968: "Vintage & Collectibles/Collectibles/Figurine",
    969: "Vintage & Collectibles/Collectibles/Glass",
    970: "Vintage & Collectibles/Collectibles/Other",
    971: "Vintage & Collectibles/Collectibles/Porcelain",
    972: "Vintage & Collectibles/Collectibles/Souvenir",
    973: "Vintage & Collectibles/Electronics/Camera",
    974: "Vintage & Collectibles/Electronics/Clock",
    975: "Vintage & Collectibles/Electronics/Game",
    976: "Vintage & Collectibles/Electronics/Other",
    977: "Vintage & Collectibles/Electronics/Radio",
    978: "Vintage & Collectibles/Electronics/Telephone",
    979: "Vintage & Collectibles/Electronics/Television",
    980: "Vintage & Collectibles/Electronics/Video Game",
    981: "Vintage & Collectibles/Furniture/Chair",
    982: "Vintage & Collectibles/Furniture/Entertainment",
    983: "Vintage & Collectibles/Furniture/Storage",
    984: "Vintage & Collectibles/Home Decor/Basket",
    985: "Vintage & Collectibles/Home Decor/Box",
    986: "Vintage & Collectibles/Home Decor/Candle Holder",
    987: "Vintage & Collectibles/Home Decor/Frame",
    988: "Vintage & Collectibles/Home Decor/Lighting",
    989: "Vintage & Collectibles/Home Decor/Linens",
    990: "Vintage & Collectibles/Home Decor/Other",
    991: "Vintage & Collectibles/Home Decor/Pillow",
    992: "Vintage & Collectibles/Home Decor/Planter",
    993: "Vintage & Collectibles/Home Decor/Tray",
    994: "Vintage & Collectibles/Home Decor/Vase",
    995: "Vintage & Collectibles/Home Decor/Wall Hanging",
    996: "Vintage & Collectibles/Housewares/Bowl",
    997: "Vintage & Collectibles/Housewares/Box",
    998: "Vintage & Collectibles/Housewares/Ceramic",
    999: "Vintage & Collectibles/Housewares/Coaster",
    1000: "Vintage & Collectibles/Housewares/Cup",
    1001: "Vintage & Collectibles/Housewares/Glass",
    1002: "Vintage & Collectibles/Housewares/Magnet",
    1003: "Vintage & Collectibles/Housewares/Other",
    1004: "Vintage & Collectibles/Housewares/Plate",
    1005: "Vintage & Collectibles/Housewares/Pot Holder",
    1006: "Vintage & Collectibles/Housewares/Table",
    1007: "Vintage & Collectibles/Housewares/Tray",
    1008: "Vintage & Collectibles/Jewelry/Bracelet",
    1009: "Vintage & Collectibles/Jewelry/Brooch",
    1010: "Vintage & Collectibles/Jewelry/Earrings",
    1011: "Vintage & Collectibles/Jewelry/Necklace",
    1012: "Vintage & Collectibles/Jewelry/Other",
    1013: "Vintage & Collectibles/Jewelry/Pendant",
    1014: "Vintage & Collectibles/Jewelry/Ring",
    1015: "Vintage & Collectibles/Jewelry/Watch",
    1016: "Vintage & Collectibles/Other/Other",
    1017: "Vintage & Collectibles/Paper Ephemera/Advertisement",
    1018: "Vintage & Collectibles/Paper Ephemera/Game",
    1019: "Vintage & Collectibles/Paper Ephemera/Map",
    1020: "Vintage & Collectibles/Paper Ephemera/Other",
    1021: "Vintage & Collectibles/Paper Ephemera/Postcard",
    1022: "Vintage & Collectibles/Paper Ephemera/Stamps",
    1023: "Vintage & Collectibles/Serving/Bowl",
    1024: "Vintage & Collectibles/Serving/Butter Dish",
    1025: "Vintage & Collectibles/Serving/Casserole",
    1026: "Vintage & Collectibles/Serving/Cream and Sugar Set",
    1027: "Vintage & Collectibles/Serving/Dinnerware Set",
    1028: "Vintage & Collectibles/Serving/Flatware",
    1029: "Vintage & Collectibles/Serving/Glassware",
    1030: "Vintage & Collectibles/Serving/Mug",
    1031: "Vintage & Collectibles/Serving/Other",
    1032: "Vintage & Collectibles/Serving/Pitcher",
    1033: "Vintage & Collectibles/Serving/Plate",
    1034: "Vintage & Collectibles/Serving/Platter",
    1035: "Vintage & Collectibles/Serving/Salt and Pepper Shakers",
    1036: "Vintage & Collectibles/Serving/Teacup",
    1037: "Vintage & Collectibles/Serving/Teapot",
    1038: "Vintage & Collectibles/Serving/Tray",
    1039: "Vintage & Collectibles/Serving/Tumbler",
    1040: "Vintage & Collectibles/Supplies/Bead",
    1041: "Vintage & Collectibles/Supplies/Button",
    1042: "Vintage & Collectibles/Supplies/Cabochon",
    1043: "Vintage & Collectibles/Supplies/Chain",
    1044: "Vintage & Collectibles/Supplies/Charm",
    1045: "Vintage & Collectibles/Supplies/Fabric",
    1046: "Vintage & Collectibles/Supplies/Finding",
    1047: "Vintage & Collectibles/Supplies/Other",
    1048: "Vintage & Collectibles/Supplies/Pattern",
    1049: "Vintage & Collectibles/Supplies/Trim",
    1050: "Vintage & Collectibles/Supplies/Yarn",
    1051: "Vintage & Collectibles/Supplies/Zipper",
    1052: "Vintage & Collectibles/Toy/Action Figure",
    1053: "Vintage & Collectibles/Toy/Animal",
    1054: "Vintage & Collectibles/Toy/Block",
    1055: "Vintage & Collectibles/Toy/Car",
    1056: "Vintage & Collectibles/Toy/Children",
    1057: "Vintage & Collectibles/Toy/Doll",
    1058: "Vintage & Collectibles/Toy/Electronic",
    1059: "Vintage & Collectibles/Toy/Game",
    1060: "Vintage & Collectibles/Toy/Other",
    1061: "Vintage & Collectibles/Toy/Puzzle",
    1062: "Vintage & Collectibles/Toy/Sport",
    1063: "Vintage & Collectibles/Trading Cards/Action, Adventure",
    1064: "Vintage & Collectibles/Trading Cards/Animation",
    1065: "Vintage & Collectibles/Trading Cards/Comic",
    1066: "Vintage & Collectibles/Trading Cards/Historical, Military",
    1067: "Vintage & Collectibles/Trading Cards/Other",
    1068: "Vintage & Collectibles/Trading Cards/Sci-Fi, Fantasy",
    1069: "Vintage & Collectibles/Trading Cards/Sports",
    1070: "Vintage & Collectibles/Trading Cards/Vintage",
    1071: "Women/Athletic Apparel/Jackets",
    1072: "Women/Athletic Apparel/Jerseys",
    1073: "Women/Athletic Apparel/Other",
    1074: "Women/Athletic Apparel/Pants, Tights, Leggings",
    1075: "Women/Athletic Apparel/Shirts & Tops",
    1076: "Women/Athletic Apparel/Shorts",
    1077: "Women/Athletic Apparel/Skirts, Skorts & Dresses",
    1078: "Women/Athletic Apparel/Snowsuits & Bibs",
    1079: "Women/Athletic Apparel/Socks",
    1080: "Women/Athletic Apparel/Sports Bras",
    1081: "Women/Athletic Apparel/Tracksuits & Sweats",
    1082: "Women/Athletic Apparel/Vests",
    1083: "Women/Coats & Jackets/Cape",
    1084: "Women/Coats & Jackets/Fleece Jacket",
    1085: "Women/Coats & Jackets/Jean Jacket",
    1086: "Women/Coats & Jackets/Military",
    1087: "Women/Coats & Jackets/Motorcycle",
    1088: "Women/Coats & Jackets/Other",
    1089: "Women/Coats & Jackets/Parka",
    1090: "Women/Coats & Jackets/Peacoat",
    1091: "Women/Coats & Jackets/Poncho",
    1092: "Women/Coats & Jackets/Puffer",
    1093: "Women/Coats & Jackets/Raincoat",
    1094: "Women/Coats & Jackets/Trench",
    1095: "Women/Coats & Jackets/Vest",
    1096: "Women/Coats & Jackets/Windbreaker",
    1097: "Women/Coats & Jackets/Wool",
    1098: "Women/Dresses/Above Knee, Mini",
    1099: "Women/Dresses/Asymmetrical Hem",
    1100: "Women/Dresses/Full-Length",
    1101: "Women/Dresses/Knee-Length",
    1102: "Women/Dresses/Mid-Calf",
    1103: "Women/Dresses/Other",
    1104: "Women/Jeans/Boot Cut",
    1105: "Women/Jeans/Boyfriend",
    1106: "Women/Jeans/Capri, Cropped",
    1107: "Women/Jeans/Cargo",
    1108: "Women/Jeans/Flare",
    1109: "Women/Jeans/Leggings",
    1110: "Women/Jeans/Other",
    1111: "Women/Jeans/Overalls",
    1112: "Women/Jeans/Relaxed",
    1113: "Women/Jeans/Slim, Skinny",
    1114: "Women/Jeans/Straight Leg",
    1115: "Women/Jeans/Wide Leg",
    1116: "Women/Jewelry/Bracelets",
    1117: "Women/Jewelry/Earrings",
    1118: "Women/Jewelry/Necklaces",
    1119: "Women/Jewelry/Rings",
    1120: "Women/Maternity/Athletic Apparel",
    1121: "Women/Maternity/Coats & Jackets",
    1122: "Women/Maternity/Dresses",
    1123: "Women/Maternity/Jeans",
    1124: "Women/Maternity/Other",
    1125: "Women/Maternity/Pants",
    1126: "Women/Maternity/Skirts",
    1127: "Women/Maternity/Suits & Blazers",
    1128: "Women/Maternity/Sweaters",
    1129: "Women/Maternity/Tops & Blouses",
    1130: "Women/Other/Other",
    1131: "Women/Pants/Capris, Cropped",
    1132: "Women/Pants/Cargo",
    1133: "Women/Pants/Casual Pants",
    1134: "Women/Pants/Corduroys",
    1135: "Women/Pants/Dress Pants",
    1136: "Women/Pants/Khakis, Chinos",
    1137: "Women/Pants/Leather",
    1138: "Women/Pants/Linen",
    1139: "Women/Pants/Other",
    1140: "Women/Shoes/Athletic",
    1141: "Women/Shoes/Boots",
    1142: "Women/Shoes/Fashion Sneakers",
    1143: "Women/Shoes/Flats",
    1144: "Women/Shoes/Loafers & Slip-Ons",
    1145: "Women/Shoes/Mules & Clogs",
    1146: "Women/Shoes/Other",
    1147: "Women/Shoes/Outdoor",
    1148: "Women/Shoes/Oxfords",
    1149: "Women/Shoes/Pumps",
    1150: "Women/Shoes/Sandals",
    1151: "Women/Shoes/Slippers",
    1152: "Women/Shoes/Work & Safety",
    1153: "Women/Skirts/A-Line",
    1154: "Women/Skirts/Asymmetrical",
    1155: "Women/Skirts/Bubble",
    1156: "Women/Skirts/Full Skirt",
    1157: "Women/Skirts/Maxi",
    1158: "Women/Skirts/Mini",
    1159: "Women/Skirts/Other",
    1160: "Women/Skirts/Peasant",
    1161: "Women/Skirts/Pleated",
    1162: "Women/Skirts/Straight, Pencil",
    1163: "Women/Skirts/Tiered",
    1164: "Women/Skirts/Wrap",
    1165: "Women/Suits & Blazers/Blazer",
    1166: "Women/Suits & Blazers/Dress Suit",
    1167: "Women/Suits & Blazers/Other",
    1168: "Women/Suits & Blazers/Pant Suit",
    1169: "Women/Suits & Blazers/Skirt Suit",
    1170: "Women/Sweaters/Cardigan",
    1171: "Women/Sweaters/Collared",
    1172: "Women/Sweaters/Cowl Neck",
    1173: "Women/Sweaters/Crewneck",
    1174: "Women/Sweaters/Full Zip",
    1175: "Women/Sweaters/Henley",
    1176: "Women/Sweaters/Hooded",
    1177: "Women/Sweaters/Other",
    1178: "Women/Sweaters/Poncho",
    1179: "Women/Sweaters/Scoop Neck",
    1180: "Women/Sweaters/Shrug",
    1181: "Women/Sweaters/Sweatercoat",
    1182: "Women/Sweaters/Tunic",
    1183: "Women/Sweaters/Turtleneck, Mock",
    1184: "Women/Sweaters/Vest, Sleeveless",
    1185: "Women/Sweaters/V-Neck",
    1186: "Women/Sweaters/Wrap",
    1187: "Women/Swimwear/Beach Accessories",
    1188: "Women/Swimwear/Cover-Ups",
    1189: "Women/Swimwear/One-Piece",
    1190: "Women/Swimwear/Two-Piece",
    1191: "Women/Tops & Blouses/Blouse",
    1192: "Women/Tops & Blouses/Button Down Shirt",
    1193: "Women/Tops & Blouses/Halter",
    1194: "Women/Tops & Blouses/Knit Top",
    1195: "Women/Tops & Blouses/Other",
    1196: "Women/Tops & Blouses/Polo Shirt",
    1197: "Women/Tops & Blouses/Tank, Cami",
    1198: "Women/Tops & Blouses/T-Shirts",
    1199: "Women/Tops & Blouses/Tunic",
    1200: "Women/Tops & Blouses/Turtleneck",
    1201: "Women/Tops & Blouses/Wrap",
    1202: "Women/Underwear/Bras",
    1203: "Women/Underwear/G-Strings & Thongs",
    1204: "Women/Underwear/Other",
    1205: "Women/Underwear/Panties",
    1206: "Women/Underwear/Thermal Underwear",
    1207: "Women/Women's Accessories/Belts",
    1208: "Women/Women's Accessories/Hair Accessories",
    1209: "Women/Women's Accessories/Hats",
    1210: "Women/Women's Accessories/Other",
    1211: "Women/Women's Accessories/Scarves & Wraps",
    1212: "Women/Women's Accessories/Sunglasses",
    1213: "Women/Women's Accessories/Wallets",
    1214: "Women/Women's Accessories/Watches",
    1215: "Women/Women's Handbags/Backpack Style",
    1216: "Women/Women's Handbags/Baguette",
    1217: "Women/Women's Handbags/Cosmetic Bags",
    1218: "Women/Women's Handbags/Hobo",
    1219: "Women/Women's Handbags/Messenger & Crossbody",
    1220: "Women/Women's Handbags/Other",
    1221: "Women/Women's Handbags/Satchel",
    1222: "Women/Women's Handbags/Shoulder Bag",
    1223: "Women/Women's Handbags/Totes & Shoppers"
}
D